version: "2.1"

services:
  loragtwpktfwd:
    restart: always
    build:
      context: loragtwpktfwd
      args:
        - LORA_REGION=EU868
        - LORA_UDP=1680
        - SPI_SPEED=2000000
        - MINER_URL=helium.p22.de
    privileged: true
